---
author:
  - 'Martin Thurn <mthurn@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Search-AltaVista
no_index:
  directory:
    - inc
    - t
requires:
  Date::Manip: 0
  HTML::TokeParser: 0
  WWW::Search: 2.561
  WWW::Search::Test: 2.263
  perl: 5.004
version: 2.152
